name: continuous-integration
on: [push, pull_request, release]
jobs:
  build:
    name: samuel-nwoye-website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Trigger Jenkinsfile
      run: echo Triggered Jenkinsfile
      uses: jenkins/jenkins #jenkinsci/jenkinsfile-runner-github-actions/jenkinsfile-runner-prepackaged@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

