name: continuous-integration
on: [push, pull_request, release]
jobs:
  build:
    name: samuel-nwoye-website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Trigger Jenkinsfile
      run: echo Triggered Jenkinsfile
      # uses: jenkinsci/jenkins
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

